routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace'=>'User'] ,function(){
    Route::get('/' , 'UserController@index')->name('user:index');

    Route::get('/login','UserController@login')->name('user:login');
    Route::post('/login','UserController@postlogin')->name('post:user:login');
    Route::get('/logout', 'UserController@logout')->name('user:logout');

    Route::get('register' , 'UserController@signup')->name('user:signup');
    Route::post('register' , 'UserController@postsignup')->name('post:user:register');

    Route::get('/verification' , 'UserController@verify')->name('verify:user');

    Route::get('home' , 'UserController@home' )->name('user:home');
    Route::get('book' , 'BookController@show')->name('show:book');
    Route::get('/book/issue/{id}' , 'BookController@issue')->name('issue:book');
    Route::post('/book/issue/{id}' , 'BookController@postissue')->name('post:issue:book');
    Route::get('mybook/{id}' , 'BookController@userbook')->name('user:issued:book');
    Route::get('return/{id}' , 'BookController@bookreturn')->name('return:book');
});



Route::group(['prefix' => 'admin', 'namespace' => 'Admin'] ,function(){

   Route::group(['middleware' => ['guest:admin']] ,function(){
       Route::get('login' , 'LoginController@getLogin')->name('admin:login');
       Route::post('login', 'LoginController@postLogin')->name('post:admin:login');

        Route::get('password/reset' , 'ForgotPasswordController@showLinkRequestForm')->name('admin:forgot:password');
        Route::post('password/email' , 'ForgotPasswordController@sendResetLinkEmail')->name('post:admin:forgot:password');
        Route::get('password/reset/{token}' , 'ResetPasswordController@ResetForm')->name('admin:reset:password');
        Route::post('password/reset/{id}' , 'ResetPasswordController@Reset')->name('post:admin:reset:password');
   });


Route::group([
    'middleware' => 'auth:admin'
] ,function(){

    Route::get('logout' , 'LoginController@getlogout')->name('admin:logout');

    Route::resource('dashboard' , 'DashboardController');

    Route::resource('customer' , 'CustomerController');

    Route::post('approve/{id}' , 'CustomerController@approve')->name('user:approve');

    Route::resource('book' , 'BookController');

    Route::get('issuedbook' , 'BookController@issuedbook')->name('issued:book');

    Route::resource('category' ,'CategoryController');


});
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded =[];

    public function book()
    {
        return $this->hasMany(Book::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index()
    {
        $category = Category::all();

        return view('admin.category.category' ,compact('category'));
    }

    public function create()
    {
        return view('admin.category.addcategory');
    }

    public function store(CategoryRequest $request)
    {
        Category::create($request->persist());
        session()->flash('success' , 'Record has been created successfully');


        return redirect(route('category.index'));
    }

    public function edit($id)
    {
        $category = Category::find($id);

        return view('admin.category.edit', compact('category'));
    }

    public function update(CategoryRequest $request, $id)
    {
        $category = Category::find($id);
        $category->fill($request->persist())->save();

        return redirect(route('category.index'));
    }
}

resources/views/admin/category/addcategory.blade.php
@extends('admin.layout.index')

@section('content')

    <form action="{{route('category.store')}}" method="post">
        @csrf
        @include('admin.auth.messages')

        <div  style="margin-top: 10%" class="container shadow bg-light mb-5 border-dark py-4 px-4 col-md-4 col-sm-12 ">
            <div class="form-group" style="">
                <label>Name of category</label>
                <input type="text" name="category" class="form-control" id="book" placeholder="Enter name of category">
                @error('category')
                <p style="color: red">{{$message}}</p>
                @enderror
            </div>

            <button type="submit" class="btn btn-primary mb-2">Add</button>
            <a href="{{route('category.index')}}" type="submit" class="btn btn-primary mb-2">Cancel</a>
        </div>
    </form>

@endsection

resources/views/admin/category/category.blade.php
@extends('admin.layout.index')

@section('content')

    <div>
        <a href="{{route('category.create')}}" class="btn btn-primary" style="margin-left: 82%;">Add new category</a>
    </div>

    <div class="container border bg-light shadow-lg mt-5 p-5">

        @include('admin.auth.messages')
        <table class="table" id="myTable">
            <thead>
            <tr>
                <th scope="col">Sr no.</th>
                <th scope="col">Category</th>
                <th scope="col"></th>

            </tr>
            </thead>
            <tbody>
            @php
                $i = 1;
            @endphp
            @foreach($category as $category)
                <tr>
                    <th scope="row">{{$i++}}</th>
                    <td>{{$category->category}}</td>
                    <td><a href="category/{{$category->id}}/edit" class="btn"><i class="fa fa-edit" style="font-size: 25px;color: #3d8fd1"></i></a></td>
                </tr>
            @endforeach
            </tbody>
        </table>

    </div>
    <a href="{{route('dashboard.index')}}" class="btn btn-primary" style="margin-top: 2%; margin-left: 50%">Back</a>
@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.layout.index')

@section('content')

    <form action="{{route('category.update' , $category->id)}}" method="post">
        @csrf
        @method('PUT')
        @include('admin.auth.messages')

        <div  style="margin-top: 10%" class="container shadow mb-5 bg-light border-dark py-4 px-4 col-md-4 col-sm-12 ">
            <div class="form-group" style="">
                <label>Name of category</label>
                <input type="text" name="category" class="form-control" id="book" placeholder="Enter name of category" value="{{$category->category}}">
                @error('category')
                <p style="color: red">{{$message}}</p>
                @enderror
            </div>

            <button type="submit" class="btn btn-primary mb-2">Update</button>
            <a href="{{route('category.index')}}" type="submit" class="btn btn-primary mb-2">Cancel</a>
        </div>
    </form>

@endsection