routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace'=>'User'] ,function(){
    Route::get('/' , 'UserController@index')->name('user:index');

    Route::get('/login','UserController@login')->name('user:login');
    Route::post('/login','UserController@postlogin')->name('post:user:login');
    Route::get('/logout', 'UserController@logout')->name('user:logout');

    Route::get('register' , 'UserController@signup')->name('user:signup');
    Route::post('register' , 'UserController@postsignup')->name('post:user:register');

    Route::get('/verification' , 'UserController@verify')->name('verify:user');

    Route::get('home' , 'UserController@home' )->name('user:home');
    Route::get('book' , 'BookController@show')->name('show:book');
    Route::get('/book/issue/{id}' , 'BookController@issue')->name('issue:book');
    Route::post('/book/issue/{id}' , 'BookController@postissue')->name('post:issue:book');
    Route::get('mybook/{id}' , 'BookController@userbook')->name('user:issued:book');
    Route::get('return/{id}' , 'BookController@bookreturn')->name('return:book');
});



Route::group(['prefix' => 'admin', 'namespace' => 'Admin'] ,function(){

   Route::group(['middleware' => ['guest:admin']] ,function(){
       Route::get('login' , 'LoginController@getLogin')->name('admin:login');
       Route::post('login', 'LoginController@postLogin')->name('post:admin:login');

        Route::get('password/reset' , 'ForgotPasswordController@showLinkRequestForm')->name('admin:forgot:password');
        Route::post('password/email' , 'ForgotPasswordController@sendResetLinkEmail')->name('post:admin:forgot:password');
        Route::get('password/reset/{token}' , 'ResetPasswordController@ResetForm')->name('admin:reset:password');
        Route::post('password/reset/{id}' , 'ResetPasswordController@Reset')->name('post:admin:reset:password');
   });


Route::group([
    'middleware' => 'auth:admin'
] ,function(){

    Route::get('logout' , 'LoginController@getlogout')->name('admin:logout');

    Route::resource('dashboard' , 'DashboardController');

    Route::resource('customer' , 'CustomerController');

    Route::post('approve/{id}' , 'CustomerController@approve')->name('user:approve');

    Route::resource('book' , 'BookController');

    Route::get('issuedbook' , 'BookController@issuedbook')->name('issued:book');

    Route::resource('category' ,'CategoryController');


});
});

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id' , 'id');
    }
}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\BookRequest;
use App\Models\Book;
use App\Models\Category;
use App\Models\IssuedBook;
use Illuminate\Http\Request;

class BookController extends Controller
{
    public function index()
    {
        $book = Book::all();

        return view('admin.Book.book', compact('book'));
    }
    public function create()
    {
        $category = Category::all();

        return view('admin.Book.addbook', compact('category'));
    }

    public function store(BookRequest $request)
    {
        Book::create($request->persist());
        session()->flash('success' , 'Record has been created successfully');

        return redirect(route('book.index'));
    }
    public function edit($id)
    {
        $category = Category::all();
        $book = Book::find($id);

        return view('admin.Book.edit' , compact('book','category'));
    }

    public function update(BookRequest $request,$id)
    {
        $book = Book::find($id);
        $book->fill($request->persist())->save();
        session()->flash('success' , 'Record has been updated successfully');

        return redirect('admin/book');
    }

    public function destroy($id)
    {
        $book =  Book::find($id);
        $book->delete();
        session()->flash('success' , 'Record has been deleted successfully');

        return back();

    }

    public function issuedbook()
    {
        $issuedbook = IssuedBook::all();

        return view('admin.Book.issuedbook' ,compact('issuedbook'));

    }
}

app/Http/Controllers/User/BookController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Book;
use App\Models\IssuedBook;
use App\Models\User;
use App\Notifications\ReturnBook;
use Carbon\Carbon;
use Illuminate\Http\Request;

class BookController extends Controller
{
    public function show()
    {
        $book = Book::all();

        return view('user.book' , compact('book'));
    }

    public function issue($id)
    {
        $book = Book::find($id);

        return view('user.issuebook', compact('book'));
    }

    public function postissue($id)
    {
        $book = Book::find($id);
        $book->fill(
            ['quantity' => ($book->quantity) - 1]
        )->save();

        IssuedBook::create([
          'user_id' => auth()->id(),
           'book_id' => $book->id,
            'quantity' => 1,
            'return_date' => Carbon::now()->addDays(15)
        ]);

        session()->flash('success', 'Book ' . $book->book .' issued successfully');

        return redirect(route('show:book'));
    }

    public function userbook($user_id)
    {
        $issuedbook = IssuedBook::with(['book.category', 'user'])->where('user_id' ,$user_id)->get();

        return view('user.mybook' , compact( 'issuedbook'));
    }

    public function bookreturn($id)
    {
        $issuedbook = IssuedBook::find($id);
        $issuedbook->delete();

        $book = Book::find($issuedbook->book_id);
        $book->fill([
            "quantity" => $book->quantity + 1
        ])->save();
        session()->flash('success' ,'Book ' . $book->book. ' returned successfully');

        return redirect(route('user:issued:book' , auth()->id()));
    }
}

resources/views/admin/Book/addbook.blade.php
@extends('admin.layout.index')

@section('content')

    <form action="{{route('book.store')}}" method="post">
        @csrf
        @include('admin.auth.messages')

        <div class="container bg-light shadow border-dark py-4 px-4 col-md-4 col-sm-12 ">
            <div class="form-group" style="">
                <label>Name of book</label>
                <input type="text" name="book_name" class="form-control" id="book" placeholder="Enter name of book">
                @error('book')
                <p style="color: red">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <label>Author of book</label>
                <input type="text" name="author" class="form-control" id="author" placeholder="Enter name of author">
                @error('author')
                <p style="color: red">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <label>Quantity</label>
                <input type="number" name="quantity" class="form-control" id="quantity" placeholder="Enter quantity">
                @error('quantity')
                <p style="color: red">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
               <tr>
                    <td>
                        <label>Category</label>
                    </td>

                   <td>:</td>

                   <td>
                       <select name="category_id">
                           @foreach($category as $category)
                               <option value="{{$category->id}}">
                                   {{$category->category}}
                               </option>
                           @endforeach
                       </select>
                   </td>
                @error('category')
                <p style="color: red">{{$message}}</p>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary mb-2">Add</button>
            <a href="{{route('book.index')}}" type="submit" class="btn btn-primary mb-2">Cancel</a>
        </div>
    </form>

@endsection

resources/views/admin/Book/book.blade.php
@extends('admin.layout.index')

@section('content')
    <div>
    <a href="{{route('book.create')}}" class="btn btn-primary" style="margin-left: 84%;">Add new book</a>
    </div>
        <div class="container border shadow-lg mt-5 p-5 bg-light">

        @include('admin.auth.messages')
        <table class="table bg-light" id="myTable">
            <thead>
            <tr>
                <th scope="col">Sr no.</th>
                <th scope="col">Name of book</th>
                <th scope="col">Category</th>
                <th scope="col">Name of author</th>
                <th scope="col">Quantity</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            @php
                $i = 1;
            @endphp
            @foreach($book as $book)
                <tr>

                    <th scope="row">{{$i++}}</th>
                    <td>{{$book->book_name}}</td>
                    <td>{{$book->category->category}}</td>
                    <td>{{$book->author}}</td>
                    <td>{{$book->quantity}}</td>
                    <td><a href="book/{{$book->id}}/edit" class="btn"><i class="fa fa-edit" style="font-size: 25px;color: #3d8fd1"></i></a></td>
                    <td>
                        <form action="{{ route('book.destroy', $book->id) }}" method="POST">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn"><i class="fa fa-trash" style="font-size: 25px;color: red"></i></button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

    </div>
    <a href="{{route('dashboard.index')}}" class="btn btn-primary" style="margin-top: 5%; margin-left: 50%">Back</a>
@endsection

resources/views/admin/Book/edit.blade.php
@extends('admin.layout.index')

@section('content')

    <form action="{{route('book.update', $book->id)}}" method="post">
        @csrf
        @method('PUT')
        @include('admin.auth.messages')

        <div class="container shadow bg-light border-dark py-4 px-4 col-md-4 col-sm-12 ">
            <div class="form-group" style="">
                <label>Name of book</label>
                <input type="text" name="book_name" class="form-control" id="book" placeholder="Enter name of book" value="{{$book->book_name}}">
                @error('book')
                <p style="color: red">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <label>Author of book</label>
                <input type="text" name="author" class="form-control" id="author" placeholder="Enter name of author" value="{{$book->author}}">
                @error('author')
                <p style="color: red">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <label>Quantity</label>
                <input type="number" name="quantity" class="form-control" id="quantity" placeholder="Enter quantity" value="{{$book->quantity}}">
                @error('quantity')
                <p style="color: red">{{$message}}</p>
                @enderror
            </div>

            <div class="form-group">
                <tr>
                    <td>
                        <label>Category</label>
                    </td>

                    <td>:</td>

                    <td>
                        <select name="category_id">
                            @foreach($category as $category)
                                <option value="{{$category->id}}">
                                    {{$category->category}}
                                </option>
                            @endforeach
                        </select>
                    </td>
                    @error('category')
                    <p style="color: red">{{$message}}</p>
                @enderror
            </div>
            <button type="submit" class="btn btn-primary mb-2">Update</button>
            <a href="{{route('book.index')}}" class="btn btn-primary mb-2">Cancel</a><br/>
        </div>
    </form>

@endsection

resources/views/admin/Book/issuedbook.blade.php
@extends('admin.layout.index')

@section('content')

    <div class="container border shadow-lg mt-5 p-5 bg-light">

        @include('admin.auth.messages')
        <table class="table bg-light" id="myTable">
            <thead>
            <tr>
                <th scope="col">Sr no.</th>
                <th scope="col">Name of book</th>
                <th scope="col">Category</th>
                <th scope="col">Name of author</th>
                <th scope="col">Quantity</th>
                <th scope="col">Issued by</th>
                <th scope="col">Date of issue</th>

            </tr>
            </thead>
            <tbody>
            @php
                $i = 1;
            @endphp
            @foreach($issuedbook as $issuedbook)
                <tr>
                    <th scope="row">{{$i++}}</th>
                    <td>{{$issuedbook->book->book_name}}</td>
                    <td>{{$issuedbook->book->category->category}}</td>
                    <td>{{$issuedbook->book->author}}</td>
                    <td>{{$issuedbook->quantity}}</td>
                    <td>{{$issuedbook->user->name}}</td>
                    <td>{{$issuedbook->created_at->toDateString()}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

@endsection