routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace'=>'User'] ,function(){
    Route::get('/' , 'UserController@index')->name('user:index');

    Route::get('/login','UserController@login')->name('user:login');
    Route::post('/login','UserController@postlogin')->name('post:user:login');
    Route::get('/logout', 'UserController@logout')->name('user:logout');

    Route::get('register' , 'UserController@signup')->name('user:signup');
    Route::post('register' , 'UserController@postsignup')->name('post:user:register');

    Route::get('/verification' , 'UserController@verify')->name('verify:user');

    Route::get('home' , 'UserController@home' )->name('user:home');
    Route::get('book' , 'BookController@show')->name('show:book');
    Route::get('/book/issue/{id}' , 'BookController@issue')->name('issue:book');
    Route::post('/book/issue/{id}' , 'BookController@postissue')->name('post:issue:book');
    Route::get('mybook/{id}' , 'BookController@userbook')->name('user:issued:book');
    Route::get('return/{id}' , 'BookController@bookreturn')->name('return:book');
});



Route::group(['prefix' => 'admin', 'namespace' => 'Admin'] ,function(){

   Route::group(['middleware' => ['guest:admin']] ,function(){
       Route::get('login' , 'LoginController@getLogin')->name('admin:login');
       Route::post('login', 'LoginController@postLogin')->name('post:admin:login');

        Route::get('password/reset' , 'ForgotPasswordController@showLinkRequestForm')->name('admin:forgot:password');
        Route::post('password/email' , 'ForgotPasswordController@sendResetLinkEmail')->name('post:admin:forgot:password');
        Route::get('password/reset/{token}' , 'ResetPasswordController@ResetForm')->name('admin:reset:password');
        Route::post('password/reset/{id}' , 'ResetPasswordController@Reset')->name('post:admin:reset:password');
   });


Route::group([
    'middleware' => 'auth:admin'
] ,function(){

    Route::get('logout' , 'LoginController@getlogout')->name('admin:logout');

    Route::resource('dashboard' , 'DashboardController');

    Route::resource('customer' , 'CustomerController');

    Route::post('approve/{id}' , 'CustomerController@approve')->name('user:approve');

    Route::resource('book' , 'BookController');

    Route::get('issuedbook' , 'BookController@issuedbook')->name('issued:book');

    Route::resource('category' ,'CategoryController');


});
});

resources/views/admin/layout/inc/header.blade.php
{{--<a href="{{ route('admin:logout') }}">--}}
{{--    <i class="fa fa-power-off pr-3 mt-4" style="font-size: 25px"></i>--}}
{{--</a>--}}
<ul class="navbar-nav ml-auto ml-md-0">
    <li  class="nav-item dropdown">
        <a href="#" class="dropdown-toggle" style="font-size: 25px;color: #2a2a2a" data-toggle="dropdown"><i class="fa fa-user mt-3"></i></a>
        <div class="dropdown-menu dropdown-menu-right p-3" aria-labelledby="userDropdown">
            <a class="dropdown-item" style="font-size: 19px" href="{{ route('admin:logout') }}"><i class="fa fa-sign-out mr-2"></i>Logout</a>
        </div>
    </li>
</ul>

resources/views/admin/layout/inc/sidebar.blade.php
<div>
    <a class="{{ request()->is('admin/dashboard') ? 'active' : '' }}" href="{{ route('dashboard.index') }}"><i class="fa fa-home pr-2" ></i>Dashboard</a>
    <a class="{{ request()->is('admin/customer*') ? 'active' : '' }}" href="{{ route('customer.index') }}"><i class="fa fa-user pr-2" ></i>User</a>
    <a class="{{ request()->is('admin/book*') ? 'active' : '' }}" href="{{ route('book.index') }}"><i class="fa fa-book pr-2" ></i>Books</a>
    <a class="{{ request()->is('admin/issuedbook*') ? 'active' : '' }}" href="{{ route('issued:book') }}"><i class="fa fa-folder-open pr-2" ></i>Isuued book</a>
    <a class="{{ request()->is('admin/category*') ? 'active' : '' }}" href="{{ route('category.index') }}"><i class="fa fa-list pr-2" ></i>Categories</a>
</div>